### ISSUE TITLE
Ch(s)ili outsider's questions

### ISSUE THREAD

**Issue by caryfuk** [salsita/chili#1]
1. Why not use libsass? Are we depending on a functionality only present in sass gem? Probably yes, rhetorical question.
2. Would be better to use css reset because it's agnostic about styling preferences.
3. Why that?

``` Sass
   $documentMinWidth:  320px
   $documentSafeWidth: 960px
```
1. Why mapping new keywords on existing flexbox keywords? _I mean I don't like confusing flexbox syntax much, but isn't this making things even more difficult to read and understand?_

``` Sass
=distribute($args: (), $dir: row)
  $flexMap: (left: flex-start, right: flex-end, top: flex-start, bottom: flex-end, center: center)
  @if length($args) == 2
    display: flex
    align-items: map-get($flexMap, nth($args, 1)) or nth($args, 1)
    justify-content: map-get($flexMap, nth($args, 2)) or nth($args, 2)
    flex-direction: $dir
  @else
    @warn 'Invalid length of arguments \'#{length($args)}\' for distribute() in chain \'#{&}\'.'
```
1. Generally, why so much abstraction? It would make sense to me in a case when I'm building something specific and from it's specific nature, I'm repeatedly using some subset of css or repeatedly building some similar constructs out of it. But I think that can't be the thing, because it's supposed to be universal right? So it seems like, we're trying to create another 
   is the case, there should be some strong benefit for the developer to justify learning how 
   abstraction layer works.
2. Definitions like unstyled-list and unstyled-button are probably there to allow me reset some previously set styles, but why would I do that? I think it might be encouraging the developer to just don't care about structure and reset stuff. But it's mixin so it's not poluting css if it's never used.
3. Animate scss is huge and probably only a fraction of it is going to be really used, so it would make sense to define everything as mixins insteadm so that parts that are never used don't appear in generated css.
4. Wouldn't this:

``` Sass
@function em($px, $scale: 62.5%, $unit: 'em')
@return unquote(__stripUnit($px)/(.16*__stripUnit($scale)) + $unit)

@function rem($px, $scale: 62.5%)
@return em($px, $scale, 'rem')
```

behave unexpectedly if you set different font-size on body than 62.5%? and why that .16 magic constant? What if you set different font-size on body?

Also, supposed that:

``` Sass
   // 1rem = 10px
   $fontM: rem(16)
```

And that rem() just takes anything and makes rem out of it, I would expect fontM to be 160px, which would not be the case. I think the whole concept of using some units and converting them to some different units using some magic constants just makes everything a lot more difficult to understand. To be honest, I have a real difficulty understanding how the font size of rem(16) is going to render. What is the benefit of all this? I believe there must be some - it's just that I don't currently see it.

**Comment by ghost** [comment]
Thank you!

We've been over these in person, but I'll reply here also for the record.
1. libsass is behind rubysass features right now, once that's not true anymore the idea is to use `node-sass`, so the ruby requirement will be dropped asap.
2. You're right that this is preferential, I'll try to work with the reset mixin along with normalize to bring in some easy configurable choices on which type of reset/default to use. I'm thinking you would define it as a property of the `root` (html) component and not bother with the rest, would something like the following be good enough?
   
   ``` Sass
   +component(root)
     +reset(normalize|meyer|other)
   ```
3. That's the exact idea, to abstract out these fundamental repeated constructs and give them more descriptive roles, as if you were designing in photoshop rather than writing CSS. This will always be a thin ice with trust problems (how can i trust that it does what I want?), but I've spend a lot of time putting these relations together and imo when you see the working CSS output and the reusability.
4. Unstyled- mixins will move into reset() with the changes we spoke about.
5. Great point. Animate doesn't really have much uniqueness to itself (just a collection of rather widespread animation types), so I guess the way out is to rewrite it into an animation bank that isn't rendered until used on an element. I'll do exactly that over the weekend.
6. Yes, you've hit one of the current bugs, I need to move some files around so the property is part of the config and loaded before the core mixins. The comment is off by 10, fixed. Idea is to allow you to do math operations on the converted values like so in both SASS and Stylus.

``` Sass
.item
  margin: $indent * 2 // $indent = rem(10) converted from px, result 20rem
```

**Comment by ghost** [comment]
The library has changed dramatically and most of this no longer applies.

**Comment by caryfuk** [comment]
Hey @filipnaumovic I just checked the new version and this **+in syntax looks clean and useful to me**. I can imagine using it and loving it if I styled my components in a way you described. **It clearly is nicer than doing it with without your magic +in syntax.**

Please beware, **my comment is not related to how it's implemented. I rather try to explain why I don't find your solution of the problem useful in my use-case and why I think I'm better off not even needing solving the problem you're solving.** Let me explain.

Instead of redefining how the component should behave in different contexts, I always try to create a component without adding any context based exceptions to it. When I create a new context, let say header, and I want to make my link look differently within it, I rather define the exception inside the header and not in the original component. **The benefit I see in this reverse approach is that it keeps my components independent on the context.** I want to keep my components reusable and if I need some exception in a header, I rather define it in the header, because I look at it as it's header related exception. The header might not even be there and because of this, I don't want to define any header related styles inside my reusable component.

**You could argue that it might be the other way round - like the header would be the component you don't want to pollute by some exceptions. But you still gotta define the exceptions somewhere and I think I'm better off not mixing bottom->up approach with top->down approach.** It allows me to not worry about how my element is going to be rendered no matter where I use it and also it allows me to easily reuse my components in different apps without a necessity of checking whether they contain some exceptions I don't want.

As I said, if I needed to define the styles in the opposite direction for some reason - just like you do it, I really think your way of doing it would be superior.

**Comment by caryfuk** [comment]
So to sum it up, the strong point is that it is allowing you to style everything related to a single component conveniently at one place and it's doing it with nice syntax.

The weak point is probably that if you really build the styles this way, you would end up with components, which are tightly coupled with other components, which might not be wanted.

So if there was some kind of a fight, it would be a fight of component isolation versus having all styles related to a component conveniently at one place, but of course there needn't to be any fight and people can just use it if they find it handy.

**Comment by ghost** [comment]
> The weak point is probably that if you really build the styles this way, you would end up with components, which are tightly coupled with other components, which might not be wanted.

I would argue that "standalone" components are impossible to truly achieve in either case. Let's explore the most simple `header` vs `button` example again:

``` Html
<header>
  <button>Hi, I'm smaller!</button>
</header>

<button>Hi, I'm normal.</button>
```

You can pick a side and say that the change in `button` size is the business of the `header` component (which is your usecase), so you put it in `header.css`, or the other way around and make it the business of `button` in `button.css`. You most probably don't want to end up with a `button-header-relations.css` stylesheet just to describe their mutual interaction.

The reasoning for both choices is however equal, because to correctly display the finished layout of this all, you need both `header` and `button` components at the same time. The header might know that a button sitting inside of it should have smaller font or a button might know that it has smaller font while sitting in a header. Eventually, both cases will produce the same query `header button { font-size: smaller }`.

But neither choice is then actually standalone, you just arbitrarily decide which component carries the info about its relations with a different component, and this decision is many cases also tied to what's higher in the DOM tree. Imo it's an unsolvable problem of trying to abstract an architecture that is fully dependant on describing relations between these various elements, while trying to avoid doing it at the same time.

`in()` doesn't answer this issue, it just goes for the lowest common denominator instead - in actual CSS, you are in both cases styling the `button` element and changing its style attributes based on various states of the UI. If you can think of DOM tree position on the same level as a media query (eg: being some exception/state that modifies styles of your element), you are answering the problem from a practical viewpoint instead, because at the very least, you always know that you're styling a `button`.

But this also implies that the better choice is putting the relations for button in header in the `button.css` component, because that's where the element is defined. On the other hand, the button is in this case easily understandable as a part of the header, so it also makes perfect sense to put it in `header.css`.

I'm not bent on either, most of the time I would probably put something in `header` and something in `button`, maybe even based on what the actual properties are (position of button in header.css, color and style changes in button.css) and/or pick what's more intuitive to the exact structure.

Well, I think it's a choice... you could still use `in()` just to target the parent elements in your current nest and not prepend any top level parents, or use them selectively just in cases where it's somehow convenient (which imo happens a lot in with stateful components like calendars, dialogs, listings, dropdowns... or when you're working with animations that move multiple elements based on some top parent state).

I'm not directly implying either is the better way of doing things, but one of these choices is made easier with `in()`.

**Comment by caryfuk** [comment]
Can't argue with that, I think it's in other words something very similar to what I also have said. Yes the selling point of inStyle is probably that your in() makes following one of the two mentioned approaches more convenient, which is a good thing!

What I would still question is whether it's good to mix the two approaches together. I think it could be mixed, but I would find useful if there was some kind of a rule describing which to use in which cases so that you always know where to look. But this is more about thinking up some methodology rather than allowing new syntax like you're doing it with inStyle.

Maybe the best would be to just try it.

**Comment by caryfuk** [comment]
I think the new readme is now more focused on the selling point of inStyle, which is good! I would still probably somehow try to cut it shorter, but I'm not sure if it's really important to spend more time on readme.

**Comment by ghost** [comment]
Good point, I'll try to reduce the readme and make some microsite with direct examples to how you can write custom components instead. I think I'll leave the core `in()` package standalone for now as it has a lot of implications by itself and will move the frameworky things into a separate repo, which could hold some premade components. I tried to combine it into a full development scheme right away, which I see now was the wrong way to start things up. Thanks for the precious feedback!
