### ISSUE TITLE
Consider extracting helpers into a third-party dependency

### ISSUE THREAD

**Issue by KittyGiraudel** [salsita/chili#14]
Hello there,

Nice work on this tool. Have you considered using [SassyLists](https://github.com/at-import/SassyLists) to make the code of your library smaller? I see you have written a lot of functions to manipulate lists, which could live in a dedicated dependencies.

I’d be happy to help with this if you need.

Best,

**Comment by ghost** [comment]
Hello @HugoGiraudel,

And thanks! I came around SassyLists while working on the implementation. Great work on that project, IMO most of the abstractions should go straight into SASS core. There are some good reasons why I'd like to use it and some other reasons why not - perhaps you can help me find a middle ground. In no particular order, my concerns are as follows:

The tool being a single file without any additional baggage has a lot of advantages in a CSS setting IMO. Having to do a `npm install` or `bower install` before use is IMO a downgrade from 0 dependencies as of now. I could directly bundle the exact needed functions in the repo I suppose, but then...

I also use string helpers and some custom helpers and I wouldn't be able to avoid needing those, so the ~ 5 functions imported from SassyLists in one way or the other would only partially take care of the whole issue with all the functional abstractions I need to make things work. I could move my custom functions to separate files/repo too or maybe even use some "SassyStrings", but then...

Some of the functions I'm using are tweaked to do a bit more than what you'd expect from the default (like `__stringToList` trimming whitespace during the conversion from a string). It's also the reason why I namespaced all the functions, to not conflict with possibly different implementations already loaded in a random user's stack. I could also write it a bit differently to use standartized functions, but then...

The file size isn't a concern all that much for me right now, since it never influences the compiled code where it would matter and because of that, the value of the dependencies further decreases IMO. 

So overall I'm kind of undecided - using dependencies would make some of my code clearer and smaller with possibly better architecture, but comes with a price. Currently, I value the "single file with 0 remote dependencies" concept quite highly because it's nice and easy to manipulate, but it's definitely something I am open to discuss for the better of the project. I reserve the right to be wrong :)

**Comment by KittyGiraudel** [comment]
Thanks for your detailed answer. Very valid concerns you have here.

What about using [Sassdash](https://github.com/davidkpiano/sassdash) then? Sassdash is a Sass port of Lodash by David Khourshid. It’s brilliant, fully tested and works super well. I am 100% sure that would cover all your utils.

Now regarding the dependency management, I guess you could import only the dependencies you need, and have a bundling step on your end to build the dist file. This is what we have on include-media for instance. The source is divided across a dozen of file, and we just build and release a dist file, easy to copy and paste.

**Comment by ghost** [comment]
Having an intermediate bundling step for the releases sounds exactly like the solution I was missing, great suggestion. Unrelatedly, include-media must be my most favorite preprocessor lib.

:dash: _Looking into all of this_

**Comment by KittyGiraudel** [comment]
Regarding the build step, I’d be happy helping you building a Gulp pipeline if that’s something you’d be interested in.

**Comment by ghost** [comment]
Definitely! I only have a vague idea how to prepare this so far, so any help is appreciated. I've been using gulp and lodash templates before to generate some custom webfont components, but this sounds a bit more involved. Using gulp for the bundling process is just fine with me.

**Comment by KittyGiraudel** [comment]
You can have a look at how we do this at include-media: https://github.com/eduardoboucas/include-media/blob/master/Gulpfile.js#L21-L29. Basically, we just concatenate all our files to generate the dist one. Quite simple, really.

The main problem for you will be to extract only the helpers you need from Sassdash. I’ll be honest and admit I don’t think there is an easy solution out of the box. Might be a good time to ping @davidkpiano to have his opinion.
